services:
  postgres:
    image: postgres
    volumes:
      - ./01-basesuporte.sql:/docker-entrypoint-initdb.d/01-basesuporte.sql
      - ./02-basesuporte.sql:/docker-entrypoint-initdb.d/02-basesuporte.sql
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "5432:5432"